# Copyright (C) 2024 originalFactor
# 
# This file is part of embyHelp.
# 
# embyHelp is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# embyHelp is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with embyHelp.  If not, see <https://www.gnu.org/licenses/>.

allow-lan: false
bind-address: 127.0.0.1
dns:
  default-nameserver:
    - 8.8.4.4
    - 1.1.1.1
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
    - '*.lan'
  fake-ip-range: 198.18.0.1/16
  fallback:
    - 8.8.8.8
    - 1.1.1.1
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - gfw
  ipv6: false
  listen: '127.0.0.1:1053'
  nameserver:
    - 'https://doh.pub/dns-query'
    - 'https://223.6.6.6/dns-query'
  nameserver-policy:
    'geosite:!cn': 1.1.1.1
    'geosite:cn': 'https://doh.pub/dns-query'
  use-hosts: true
external-controller: '127.0.0.1:9090'
external-ui: /clash/ui
geox-url:
  geoip: 'https://jsd.onmicrosoft.cn/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat'
  geosite: >-
    https://jsd.onmicrosoft.cn/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat
  mmdb: 'https://jsd.onmicrosoft.cn/gh/Loyalsoldier/geoip@release/Country.mmdb'
ipv6: false
log-level: warning
mode: rule
profile:
  store-fake-ip: false
  store-selected: true
proxies: null
proxy-groups:
  - name: PROXY
    proxies:
      - Fallback
      - URL Test
      - Load Balance
      - Manual
      - DIRECT
    type: select
  - name: Manual
    proxies:
      []
    type: select
  - name: Fallback
    proxies:
      - Full Fallback
    type: select
  - name: URL Test
    proxies:
      - Full URL Test
    type: select
  - name: Load Balance
    proxies:
      - Full Load Balance
    type: select
  - name: Full Fallback
    proxies:
      []
    type: fallback
  - name: Full URL Test
    proxies:
      []
    type: url-test
  - name: Full Load Balance
    proxies:
      []
    type: load-balance
  - name: Advertisments
    proxies:
      - REJECT
      - DIRECT
      - PROXY
    type: select
  - name: Subscriptions
    type: select
    proxies:
      - DIRECT
      - PROXY
  - name: China
    type: select
    proxies:
      - DIRECT
      - PROXY
  - name: Apple
    type: select
    proxies:
      - DIRECT
      - PROXY
  - name: iCloud
    type: select
    proxies:
      - DIRECT
      - PROXY
  - name: Google China
    type: select
    proxies:
      - PROXY
      - DIRECT
  - name: Telegram
    type: select
    proxies:
      - PROXY
      - DIRECT
  - name: Emby
    type: select
    proxies:
      - DIRECT
      - PROXY
  - name: Others
    type: select
    proxies:
      - PROXY
      - DIRECT
proxy-providers:
  []
quic: false
rule-providers:
  apple:
    behavior: domain
    interval: 86400
    path: ./ruleset/apple.yaml
    type: http
    url: 'https://jsd.onmicrosoft.cn/gh/Loyalsoldier/clash-rules@release/apple.txt'
  applications:
    behavior: classical
    interval: 86400
    path: ./ruleset/applications.yaml
    type: http
    url: >-
      https://jsd.onmicrosoft.cn/gh/Loyalsoldier/clash-rules@release/applications.txt
  cncidr:
    behavior: ipcidr
    interval: 86400
    path: ./ruleset/cncidr.yaml
    type: http
    url: 'https://jsd.onmicrosoft.cn/gh/Loyalsoldier/clash-rules@release/cncidr.txt'
  direct:
    behavior: domain
    interval: 86400
    path: ./ruleset/direct.yaml
    type: http
    url: 'https://jsd.onmicrosoft.cn/gh/Loyalsoldier/clash-rules@release/direct.txt'
  gfw:
    behavior: domain
    interval: 86400
    path: ./ruleset/gfw.yaml
    type: http
    url: 'https://jsd.onmicrosoft.cn/gh/Loyalsoldier/clash-rules@release/gfw.txt'
  google:
    behavior: domain
    interval: 86400
    path: ./ruleset/google.yaml
    type: http
    url: 'https://jsd.onmicrosoft.cn/gh/Loyalsoldier/clash-rules@release/google.txt'
  icloud:
    behavior: domain
    interval: 86400
    path: ./ruleset/icloud.yaml
    type: http
    url: 'https://jsd.onmicrosoft.cn/gh/Loyalsoldier/clash-rules@release/icloud.txt'
  lancidr:
    behavior: ipcidr
    interval: 86400
    path: ./ruleset/lancidr.yaml
    type: http
    url: 'https://jsd.onmicrosoft.cn/gh/Loyalsoldier/clash-rules@release/lancidr.txt'
  private:
    behavior: domain
    interval: 86400
    path: ./ruleset/private.yaml
    type: http
    url: 'https://jsd.onmicrosoft.cn/gh/Loyalsoldier/clash-rules@release/private.txt'
  proxy:
    behavior: domain
    interval: 86400
    path: ./ruleset/proxy.yaml
    type: http
    url: 'https://jsd.onmicrosoft.cn/gh/Loyalsoldier/clash-rules@release/proxy.txt'
  reject:
    behavior: domain
    interval: 86400
    path: ./ruleset/reject.yaml
    type: http
    url: 'https://jsd.onmicrosoft.cn/gh/Loyalsoldier/clash-rules@release/reject.txt'
  telegramcidr:
    behavior: ipcidr
    interval: 86400
    path: ./ruleset/telegramcidr.yaml
    type: http
    url: >-
      https://jsd.onmicrosoft.cn/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt
  tld-not-cn:
    behavior: domain
    interval: 86400
    path: ./ruleset/tld-not-cn.yaml
    type: http
    url: >-
      https://jsd.onmicrosoft.cn/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt
rules:
  - 'DST-PORT,123/136/137-139,DIRECT,udp'
  - 'AND,((PROCESS-NAME,clash),(NOT,((IN-TYPE,inner)))),REJECT'
  - 'AND,((NETWORK,TCP),(DST-PORT,5228-5230)),DIRECT'
  - 'AND,((NETWORK,udp),(OR,((DST-PORT,443/80),(GEOSITE,youtube)))),DIRECT'
  - 'IP-CIDR,127.0.0.1/32,REJECT,no-resolve'
  - 'IP-CIDR,198.18.0.1/16,REJECT,no-resolve'
  - 'IP-CIDR,28.0.0.1/8,REJECT,no-resolve'
  - 'IP-CIDR6,::1/128,REJECT,no-resolve'
  - 'RULE-SET,applications,China'
  - 'DOMAIN,api.ouoboom.xyz,Subscriptions'
  - 'DOMAIN,sub.pigfarmcloud.com,Subscriptions'
  - 'DOMAIN,sub3.smallstrawberry.com,Subscriptions'
  - 'DOMAIN,swvum.no-mad-world.club,Subscriptions'
  - 'DOMAIN,update.glados-config.com,Subscriptions'
  - 'DOMAIN-KEYWORD,emby,Emby'
  - 'RULE-SET,private,DIRECT'
  - 'RULE-SET,reject,Advertisments'
  - 'GEOSITE,category-ads-all,Advertisments'
  - 'RULE-SET,icloud,iCloud'
  - 'RULE-SET,apple,Apple'
  - 'RULE-SET,google,Google China'
  - 'RULE-SET,proxy,PROXY'
  - 'RULE-SET,direct,China'
  - 'GEOSITE,CN,China'
  - 'RULE-SET,lancidr,DIRECT'
  - 'GEOIP,LAN,DIRECT'
  - 'RULE-SET,cncidr,China'
  - 'GEOIP,CN,China'
  - 'RULE-SET,telegramcidr,Telegram'
  - 'MATCH,Others'
secret: mysecret
tun:
  auto-detect-interface: true
  auto-route: true
  device: utun
  dns-hijack:
    - 'any:53'
    - 'tls://any:53'
  enable: true
  mtu: 9000
  stack: system
